apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: strings-app
    product: demo-app
    owner: suren
  name: strings-api
spec:
  replicas: 10
  selector:
    matchLabels:
      app: strings-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: strings-api
        product: demo-app
        owner: suren
    spec:
      containers:
        - image: surenmcode/strings-api
          name: strings-api
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
status: {}
