apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: strings-app
  name: strings-cache
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: strings-cache
  type: ClusterIP
status:
  loadBalancer: {}
