apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: strings-app
    product: demo-app
    owner: suren
  name: strings-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strings-cache
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: strings-cache
        product: demo-app
        owner: suren
    spec:
      containers:
        - image: redis
          name: strings-cache
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
status: {}
