apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: strings-app
  name: strings-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strings-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: strings-api
    spec:
      containers:
        - image: surenmcode/strings-api
          name: strings-api
          resources:
            requests:
              cpu: 400m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
status: {}
