apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: strings-app
  name: strings-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strings-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: strings-frontend
    spec:
      containers:
        - image: surenmcode/strings-frontend
          name: strings-frontend
          env:
            - name: API_PATH_BASE
              value: "strings-app"
          resources: {}
status: {}
