apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: strings-app
  name: strings-api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: strings-api
  type: ClusterIP
status:
  loadBalancer: {}
