apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../base
patchesStrategicMerge:
- overrides.yaml
namespace: dev
commonLabels:
  environment: dev
# kustomize edit set image surenmcode/strings-api=surenmcode/strings-api:5.5
images:
- name: redis
  newName: redis
  newTag: 6.0.9
- name: surenmcode/strings-api
  newName: surenmcode/strings-api
  newTag: main-35
- name: surenmcode/strings-frontend
  newName: surenmcode/strings-frontend
  newTag: main-35
