apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: strings-app
    environment: dev
    owner: surena
    product: demo-app
  name: strings-api  
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: strings-api
      environment: dev
  strategy: {}
  template:
    metadata:
      labels:
        app: strings-api
        environment: dev
        owner: suren
        product: demo-app
    spec:
      containers:
      - image: surenmcode/strings-api:main-43
        name: strings-api
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 300m
            memory: 64Mi
status: {}